### ISSUE TITLE
Use relationship cardinality in the LinkML export

### ISSUE THREAD

**Issue by simoneguzzi** [simoneguzzi/arrows.app#42]
Relationship cardinalities should be used to populate the `minimum_cardinality` and `maximum_cardinality` slots of the dedicated class in the LinkML export. E.g:

```yaml
PhysicianAthleteRelationship:
   is_a: Triple
   slot_usage:
      subject:
         range: Physician
      predicate:
         range: PhysicianAthletePredicate
      object:
         range: Athlete
      startingFrom:
         range: date
      salary:
         range: float
      maximum_cardinality: 0
      minimum_cardinality: 70
```
